[package]
name = "lazywrite"
version = "0.1.0"
authors = ["Richard Anaya <richard.anaya@gmail.com>"]

[dependencies]
aws_lambda = { git = "https://github.com/srijs/rust-aws-lambda", features = ["string-null-empty"] }
failure = "0.1.2"
serde_json = "1.0"
rusoto_core = "0.33.0"
rusoto_secretsmanager = "0.33.0"
lazy_static="1.1.0"
diesel = { version = "1", features = ["postgres"] }
warp = "0.1.3"
http = "0.1"

[features]
default = []
local_development = []
